/** @format */

export const subjectList = [
  {
    subId: "science",
    subName: "Science",
    subLesson: [
      "Force",
      "Pressure",
      "Energy",
      "Heat",
      "Light",
      "Electricity and Magnetism",
      "Classification of Elements",
      "Chemical Reactions and Equations",
      "Acid,Base and Salt",
      "Some Gases",
      "Metals",
      "Carbon and it's Compounds",
      "Materials used in Daily Life",
      "Human Nervous and Glandular System",
      "Chromosome and Sex Determination",
      "Reproduction",
      "Blood Circulation in Human Body",
      "Heredity",
      "Invertebrates",
      "Environment Population and Management",
      "History of Earth",
      "The Atmosphere",
      "The Universe",
    ],
  },
  {
    subId: "english",
    subName: "English",
    subLesson: [
      "Letter Writing",
      "Paragraph Writing",
      "Essay Writing",
      "Story Writing",
      "Seen Passage",
      "Application Writing",
      "Argumentative Writing",
      "Advertisement",
      "Newspaper Article",
      "Articles",
      "Transformation",
      "Question Tags",
      "Conditional Sentense",
      "Prepositions",
      "Reported Speech",
      "Causative Verb",
      "Relative Clause",
      "Subject-Verb Concord",
      "Tenses",
    ],
  },
  {
    subId: "social",
    subName: "Social Studies",
    subLesson: [
      "Our Tradistion, Values, and Norms",
      "Social Problems and solutions",
      "Civic sense",
      "Geographical Studies of Earth",
      "Our Past",
      "Economic Activities",
      "International Relation, Peace and Co-operation",
      "Infrastructures for Development",
      "We and Our Community",
    ],
  },
  {
    subId: "comp_math",
    subName: "Compulsory Mathematics",
    subLesson: [
      "Sets",
      "Time and Work",
      "Profit and Loss",
      "Compound Interest",
      "Population Growth and Compound Depreciation",
      "Area of Triangle",
      "Triangular Prism",
      "Cylinder",
      "Sphere and Hemisphere",
      "Cone",
      "Pyramid",
      "Algebra",
      "Triangle",
      "Construction",
      "Circle",
      "Experimental Verifications of Theorems",
      "Trigonometry",
      "Statistics",
      "Probability",
    ],
  },
  {
    subId: "env_pop_health",
    subName: "Environment, Population and Health",
    subLesson: [
      "Demography",
      "Quality of Life",
      "Environmental Status of Life",
      "Biodiversity",
      "Population, Environment and Development",
      "Disease, Nutrition, Tobacco, Alcohol, and Drugs",
      "Community Health",
    ],
  },
  {
    subId: "opt_math",
    subName: "Optional Mathematics",
    subLesson: [
      "Functons and Polynomials",
      "Sequence and Series",
      "Matrix",
      "Trigonometric Ratios of Compound Angles",
      "Trigonometric ratios of Multiple Angles",
      "Trigonometric Ratios of Sub Multiple Angles",
      "Transformation of Trigonometric Formulae",
      "Conditional Trigonometric Identities",
      "Solutions of Trigonometric Equations",
      "Height and Distance",
      "Vector",
      "Angles between Two Linee",
      "Pairs of Straight Lines",
      "Circle",
      "Statistics",
      "Combination of Transformations",
      "Transformation using Matrix",
    ],
  },
  {
    subId: "computer",
    subName: "Computer Science",
    subLesson: [
      "Cyber law and Computer Ethics",
      "Networking and Telecommunication",
      "Internet and its Services",
      "Computer Security",
      "Computer Virus",
      "Multimedia and its Applications",
      "Computer Number System",
      "Database Management System",
      "Modular Programming in QBSIC",
      "File Handling in QBASIC",
      "Structured Programming - C language",
    ],
  },
  {
    subId: "accountant",
    subName: "Accountancy",
    subLesson: [
      "Office Procedure",
      "Filing and Indexing",
      "Trade",
      "Financial Instituitions",
      "Trial Balance",
      "Final Accounts",
      "Government Accounting",
      "Journal Voucher",
      "Budget Sheet",
      "Monthly Statement",
      "Bank Cash Book",
      "Petty Cash Book",
    ],
  },
];
